# Generated by Django 6.1.1 on 2026-09-10 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendWindow',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravewright_campaigns.membership')),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('text', models.TextField(max_length=2000)),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='gravewright_campaigns.campaign')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['campaign', 'id'], name='chat_campaign_history')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'author', 'request_id'), name='chat_unique_submission')],
            },
        ),
    ]
