# Generated by Django 6.1.1 on 2026-09-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_chat', '0002_message_roll_message_visibility_recipient'),
        ('gravewright_maps', '0002_scenestate_sceneobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='gravewright_maps.scene'),
        ),
        migrations.AlterField(
            model_name='message',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('gm', 'GM'), ('whisper', 'Whisper')], default='public', max_length=8),
        ),
    ]
