# Generated by Django 6.1.1 on 2026-09-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_chat', '0003_message_scene_alter_message_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
