# Generated by Django 6.1.1 on 2026-09-11 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_chat', '0004_message_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.FileField(blank=True, upload_to='chat/cards/')),
                ('back', models.FileField(blank=True, upload_to='chat/cards/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_attachments', to='gravewright_chat.message')),
            ],
        ),
    ]
