from __future__ import annotations

from enum import StrEnum


class TransportEvent(StrEnum):
    ERROR = "error"

    MEMBER_JOINED = "member.joined"
    MEMBER_REMOVED = "member.removed"
    PRESENCE_UPDATED = "presence.updated"
    PRESENCE_SNAPSHOT = "presence.snapshot"
    LOBBY_UPDATED = "lobby.updated"

    CAMPAIGN_SYSTEM_CHANGED = "campaign.system.changed"
    CAMPAIGN_PACKAGES_CHANGED = "campaign.packages.changed"
    CAMPAIGN_TABLE_SETTINGS_CHANGED = "campaign.table_settings.changed"

    CHAT_MESSAGE_CREATED = "chat.message.created"
    CHAT_MESSAGE_DELETED = "chat.message.deleted"
    CHAT_MESSAGES_CLEARED = "chat.messages.cleared"

    JOURNAL_CREATED = "journal.created"
    JOURNAL_UPDATED = "journal.updated"
    JOURNAL_DELETED = "journal.deleted"
    JOURNAL_ACCESS_CHANGED = "journal.access_changed"
    HANDOUT_ACCESS_CHANGED = "handout.access_changed"
    HANDOUT_PRESENTED = "handout.presented"
    QUEST_STATUS_CHANGED = "quest.status_changed"
    QUEST_OBJECTIVE_UPDATED = "quest.objective_updated"
    QUEST_BOARD_UPDATED = "quest_board.updated"

    ACTOR_CREATED = "actor.created"
    ACTOR_UPDATED = "actor.updated"
    ACTOR_DELETED = "actor.deleted"
    ITEM_CREATED = "item.created"
    ITEM_UPDATED = "item.updated"
    ITEM_DELETED = "item.deleted"
    SHEET_DATA_UPDATED = "sheet.data.updated"
    SHEET_DROP_APPLIED = "sheet.drop.applied"
    CONTENT_ENTRY_IMPORTED = "content.entry.imported"

    TOKEN_CREATED = "token.created"
    TOKEN_MOVED = "token.moved"
    SCENE_ZONES_CHANGED = "scene.zones.changed"
    ZONE_ENTERED = "zone.entered"
    ZONE_LEFT = "zone.left"
    ZONE_CROSSED = "zone.crossed"
    INTERACTION_CHANGED = "interaction.changed"
    SCENE_OBJECTS_CHANGED = "scene.objects.changed"
    SCENE_OBJECT_INTERACTED = "scene.object.interacted"
    UI_PRESENTATION_CHANGED = "ui.presentation.changed"
    AUDIO_CHANGED = "audio.changed"
    NAVIGATION_SCENE_CHANGED = "navigation.scene.changed"
    INPUT_BINDING_CHANGED = "input.binding.changed"
    TOKEN_UPDATED = "token.updated"
    TOKEN_DELETED = "token.deleted"

    TOKENS_SNAPSHOT = "tokens.snapshot"
    TOKENS_CREATED = "tokens.created"
    TOKENS_UPDATED = "tokens.updated"
    TOKENS_MOVED = "tokens.moved"
    TOKENS_DELETED = "tokens.deleted"
    TOKENS_VISIBILITY_CHANGED = "tokens.visibility_changed"
    TOKENS_CONDITIONS_UPDATED = "tokens.conditions.updated"

    ROLL_CREATED = "roll.created"
    RULES_ACTION_COMPLETED = "rules.action.completed"

    CARDS_STATE_UPDATED = "cards.state.updated"
    PDF_ANNOTATIONS_CHANGED = "pdf.annotations.changed"
    PDF_PRESENTATION_CHANGED = "pdf.presentation.changed"
    TOKEN_TARGETS_CHANGED = "token.targets.changed"
    SCENE_MEASUREMENTS_CHANGED = "scene.measurements.changed"
    AUTOMATION_JOB_CHANGED = "automation.job.changed"
    WORKFLOW_CHANGED = "workflow.changed"
    GAMEPLAY_FLOW_CHANGED = "gameplay.flow.changed"
    TIMELINE_CHANGED = "timeline.changed"
    TOKENS_TRANSFERRED = "tokens.transferred"

    ASSETS_LIBRARY_UPDATED = "assets.library.updated"
    SCENE_IMAGES_UPDATED = "scene.images.updated"
    SCENE_WALLS_UPDATED = "scene.walls.updated"
    SCENE_LIGHTS_UPDATED = "scene.lights.updated"
    SCENE_PARTICLES_UPDATED = "scene.particles.updated"
    SCENE_SHADERS_UPDATED = "scene.shaders.updated"
    SCENE_SHADER_PRESETS_UPDATED = "scene.shader_presets.updated"

    SCENE_UPLOAD_PROGRESS = "scene.upload.progress"
    SCENE_CREATED = "scene.created"
    SCENE_ACTIVATED = "scene.activated"
    SCENE_UPDATED = "scene.updated"
    SCENE_DELETED = "scene.deleted"
    SCENE_LAYER_CREATED = "scene.layer.created"
    SCENE_LAYER_UPDATED = "scene.layer.updated"
    SCENE_LAYER_DELETED = "scene.layer.deleted"
    SCENE_CHUNK_UPDATED = "scene.chunk.updated"
    SCENE_CHUNK_DELETED = "scene.chunk.deleted"
    SCENE_GM_PREFETCH_HINT = "scene.gm_prefetch.hint"

    FOG_UPDATED = "fog.updated"

    BOARD_PING = "board.ping"
    BOARD_AREA_MARKER_UPSERTED = "board.area_marker.upserted"
    BOARD_AREA_MARKER_DELETED = "board.area_marker.deleted"
    BOARD_AREA_MARKER_CLEARED = "board.area_marker.cleared"
    BOARD_DRAW_UPSERTED = "board.draw.upserted"
    BOARD_DRAW_CLEARED = "board.draw.cleared"
    BOARD_MEASURE_FLASHED = "board.measure.flashed"
    BOARD_MEASURE_DELETED = "board.measure.deleted"
    BOARD_MEASURE_CLEARED = "board.measure.cleared"



    COMBAT_STARTED = "combat.started"
    COMBAT_UPDATED = "combat.updated"
    COMBAT_ENDED = "combat.ended"
