# Generated by Django 6.1.1 on 2026-09-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gravewright_campaigns", "0001_initial"),
        ("gravewright_maps", "0005_tile_byte_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleSet",
            fields=[
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gravewright_campaigns.campaign",
                    ),
                ),
                ("revision", models.CharField(default="0", max_length=32)),
                ("modules", models.JSONField(default=dict)),
                ("replacements", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=120)),
                ("version", models.CharField(max_length=60)),
                ("digest", models.CharField(max_length=64)),
                ("manifest", models.JSONField()),
                ("record", models.JSONField()),
                ("revoked", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module_id", "version"), name="module_unique_release"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContextLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=120)),
                ("mount", models.CharField(max_length=128)),
                ("revision", models.CharField(max_length=32)),
                ("closed", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gravewright_campaigns.campaign",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gravewright_maps.scene",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "user", "module_id", "mount"),
                        name="module_unique_lease",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModuleValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=120)),
                ("user_key", models.CharField(blank=True, max_length=36)),
                ("key", models.CharField(max_length=240)),
                ("value", models.JSONField()),
                ("revision", models.CharField(max_length=32)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gravewright_campaigns.campaign",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "module_id", "user_key", "key"),
                        name="module_unique_value",
                    )
                ],
            },
        ),
    ]
