# Generated by Django 6.1.1 on 2026-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='global_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='locale_catalogs',
            field=models.JSONField(default=dict),
        ),
    ]
