# Generated by Django 6.1.1 on 2026-09-10 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='gravewright_campaigns.membership')),
            ],
        ),
    ]
