# Generated by Django 6.1.1 on 2026-09-10 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_links', to='gravewright_journals.journal')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_links', to='gravewright_journals.journal')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('board', 'quest'), name='journal_unique_board_quest')],
            },
        ),
    ]
