# Generated by Django 6.1.1 on 2026-09-10 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_compendiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.UUIDField()),
                ('kind', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=240)),
                ('file', models.FileField(upload_to='compendiums/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gravewright_compendiums.entry')),
            ],
        ),
    ]
