# Generated by Django 6.1.1 on 2026-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_compendiums', '0002_entryasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bundle',
            field=models.FileField(blank=True, upload_to='compendiums/bundles/'),
        ),
    ]
