# Generated by Django 6.1.1 on 2026-09-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        ('gravewright_compendiums', '0003_entry_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=120)),
                ('pack', models.CharField(max_length=120)),
                ('role', models.CharField(default='player', max_length=16)),
                ('level', models.CharField(default='none', max_length=8)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'collection', 'pack', 'role'), name='content_unique_access')],
            },
        ),
    ]
