"""Spanish product strings; untranslated legacy keys fall back to English."""
CATALOG={
"inside.settings.locale.en":"Inglés","inside.settings.locale.pt-BR":"Portugués de Brasil","inside.settings.locale.es":"Español",
"game.scene_images.title":"Imágenes del mapa","game.scene_images.search":"Buscar imágenes","game.scene_images.hint":"Arrastra una imagen al mapa para colocarla.","game.scene_images.empty":"Todavía no se ha subido ninguna imagen a esta campaña.","game.scene_images.no_match":"Ninguna imagen coincide con esta búsqueda.","game.scene_images.minimize":"Minimizar","game.scene_images.close":"Cerrar",
"game.lighting_panel.title":"Visibilidad","game.lighting_panel.tool":"Visibilidad de la escena","game.lighting_panel.mode":"Modo","game.lighting_panel.mode_none":"Visión total","game.lighting_panel.mode_none_hint":"El mapa entero es visible para todos. Nada oculta nada.","game.lighting_panel.mode_dynamic":"Iluminación dinámica","game.lighting_panel.mode_dynamic_hint":"Los jugadores solo ven lo que alcanzan sus fichas y los focos. Los muros bloquean la visión.","game.lighting_panel.mode_manual":"Iluminación manual","game.lighting_panel.mode_manual_hint":"Pintas a mano lo revelado, ignorando fichas y focos.","game.lighting_panel.darkness":"Oscuridad","game.lighting_panel.darkness_hint":"Cuánto se oscurece el mapa con la luz apagada. La visión total lo ignora.","game.lighting_panel.lights":"Luz de la escena","game.lighting_panel.lights_on":"Encendida","game.lighting_panel.lights_off":"Apagada","game.lighting_panel.lights_hint":"Apaga y enciende sin perder la oscuridad ajustada arriba.","game.lighting_panel.no_scene":"Carga una escena para ajustar la visibilidad.","game.lighting_panel.save_failed":"No se pudo cambiar la visibilidad de la escena.",
"game.tool_dock.layers.composition":"Artística","game.tool_dock.layers.composition_hint":"Imágenes y sonidos de la escena",
"game.sound.images":"Imágenes","game.sound.sounds":"Sonidos","game.sound.scene":"Escena","game.sound.soundscape":"Paisaje sonoro","game.sound.no_soundscape":"Ningún paisaje sonoro seleccionado","game.sound.spatial":"Sonidos espaciales","game.sound.place":"Colocar sonido espacial","game.sound.library":"Biblioteca","game.sound.empty":"No hay sonidos espaciales en esta escena.","game.sound.activate":"Activar","game.sound.edit":"Editar","game.sound.effects":"Efectos de sonido","game.sound.music":"Música","game.sound.ambience":"Ambiente","game.sound.playlists":"Listas de reproducción","game.sound.soundscapes":"Paisajes sonoros","game.sound.mixer":"Mezclador","game.sound.master":"General","game.sound.sfx":"Efectos","game.sound.mute":"Silenciar","game.sound.enable":"Activar","game.sound.disable":"Desactivar","game.sound.delete":"Eliminar sonido espacial","game.sound.spatial_one":"Sonido espacial","game.sound.playing":"Reproduciendo","game.sound.all":"Todos","game.sound.new":"Nuevo sonido","game.sound.new_effect":"Nuevo efecto de sonido","game.sound.placement_hint":"Haz clic y arrastra en el mapa para posicionar el sonido y definir su radio. Pulsa Esc para cancelar.","game.sound.now_playing":"Reproduciendo ahora","game.sound.playing_help":"La música, los ambientes y los efectos activos aparecen aquí.","game.sound.soundscape_help":"Combina música, ambiente y efectos para esta escena.","game.sound.audio_asset":"Asset de audio","game.sound.name":"Nombre","game.sound.kind":"Clasificación","game.sound.gain":"Ganancia","game.sound.cancel":"Cancelar","game.sound.save":"Guardar",
"game.sound.ambient_sound":"Sonido ambiente","game.sound.sound_effect":"Efecto de sonido","game.sound.ambient_help":"Música reproducida sin posición en el mapa","game.sound.effect_help":"Emisores posicionados en la escena",
"game.sound.source":"Fuente","game.sound.placement":"Posicionamiento","game.sound.radius":"Radio del efecto","game.sound.playback":"Reproducción","game.sound.falloff":"Atenuación por distancia","game.sound.loop":"Repetir continuamente","game.sound.acoustics":"Acústica","game.sound.acoustics_help":"Las paredes y puertas controlan el paso, la atenuación y el bloqueo sin reiniciar la reproducción.","game.sound.state":"Estado","game.sound.enabled":"Activo","game.sound.constant":"Constante","game.sound.linear":"Lineal","game.sound.smooth":"Suave","game.sound.select":"Seleccionar","game.sound.preview":"Previsualizar","game.sound.play":"Reproducir",
"game.sound.one_shot":"Una vez","game.sound.radius_help":"Los tokens fuera de este radio no oyen el efecto de sonido.","game.sound.max_volume":"Volumen máximo","game.sound.volume_help":"El volumen es máximo en el centro y disminuye progresivamente hacia el borde.","game.sound.activation":"Activación","game.sound.enabled_help":"Activa o desactiva temporalmente este emisor.","game.sound.constrained_walls":"Restringir por paredes y puertas",
"game.sound.empty_spatial":"No se ha colocado ningún efecto de sonido en esta escena.","game.sound.empty_ambient":"No hay sonidos ambiente disponibles. Sube uno en GM → Recursos.","game.sound.empty_library":"No hay sonidos disponibles.","game.sound.search_ambient":"Buscar sonidos ambiente","game.sound.no_ambient_match":"Ningún sonido ambiente coincide con la búsqueda.",
"game.assets.root":"Raíz","game.assets.image":"Imagen","game.assets.audio":"Audio","game.assets.delete":"Eliminar recurso","game.assets.place_scene":"Colocar en la escena","game.assets.upload_image":"Subir imagen","game.assets.upload_audio":"Subir audio","game.assets.upload_pdf":"Subir ficha PDF","game.assets.title":"Recursos","game.assets.search":"Buscar recursos","game.assets.filter_kind":"Filtrar por tipo","game.assets.kind_all":"Todos","game.assets.kind_image":"Imágenes","game.assets.kind_audio":"Audios","game.assets.kind_pdf":"PDF","game.assets.import_package":"Importar paquete","game.assets.new_folder":"Nueva carpeta","game.assets.create_folder":"Crear carpeta","game.assets.empty_folder":"Esta carpeta está vacía.","game.assets.no_match":"Nada coincide con la búsqueda.","game.assets.no_kind":"No hay recursos de este tipo en la carpeta.","game.assets.errors.upload_failed":"No se pudo subir el archivo.","game.assets.errors.too_large":"El archivo es demasiado grande.","game.assets.errors.unsupported_type":"Formato de archivo no compatible.","game.assets.errors.pdf_system_required":"Las fichas PDF requieren el sistema PDF.",
"game.settings.ping_color":"Color de identificación","game.settings.ping_color_hint":"Se utiliza en tus pings, marcadores y mediciones para identificarte en la mesa."
}
