# Generated by Django 6.1.1 on 2026-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='locale',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
