# Generated by Django 6.1.1 on 2026-09-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
                ('error', models.CharField(blank=True, max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'author', 'request_id'), name='dice_unique_submission')],
            },
        ),
    ]
