import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { MODULE_KINDS, MODULE_PROVIDERS, type ModuleKind, type ModuleProvider } from "@gravewright/sdk";

const REQUIRED: Partial<Record<ModuleKind, string[]>> = {
  server: ["start", "stop", "route", "middleware", "slot"],
};

export interface ScaffoldOptions {
  root: string;
  kind: string;
  name: string;
  provider?: string;
  complete?: boolean;
  dryRun?: boolean;
}

export interface ScaffoldResult { directory: string; files: string[]; }

export function normalizeName(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function method(name: string): string {
  if (name === "route" || name === "middleware" || name === "slot") return `      ${name}() { return () => {}; },`;
  return `      async ${name}() {},`;
}

export async function scaffoldModule(options: ScaffoldOptions): Promise<ScaffoldResult> {
  if (!MODULE_KINDS.includes(options.kind as ModuleKind)) throw new Error(`Unknown module kind "${options.kind}"`);
  const provider = options.provider ?? "community";
  if (!MODULE_PROVIDERS.includes(provider as ModuleProvider)) throw new Error(`Unknown provider "${provider}"`);
  const name = normalizeName(options.name);
  if (!name) throw new Error("Module name must contain letters or numbers");
  const directory = path.join(options.root, "modules", name);
  if (await access(directory).then(() => true, () => false)) throw new Error(`Module directory already exists: ${directory}`);
  const required = REQUIRED[options.kind as ModuleKind] ?? [];
  const interfaceName = `${name.split("-").map((part) => part[0]?.toUpperCase() + part.slice(1)).join("")}API`;
  const manifest = {
    name, kind: options.kind, provider, version: "0.1.0", entry: "./index.ts", types: "./types.ts",
    exports: { get: required },
  };
  const index = [
    'import { defineModule, type Context } from "@gravewright/sdk";', "",
    "export default defineModule({",
    `  name: ${JSON.stringify(name)},`,
    `  kind: ${JSON.stringify(options.kind)},`,
    `  provider: ${JSON.stringify(provider)},`,
    '  version: "0.1.0",',
    `  exports: { get: ${JSON.stringify(required)} },`,
    `  create(${options.complete ? "ctx" : "_ctx"}: Context) {`,
    ...(options.complete ? [
      "    ctx.diagnostic.record({",
      `      event: ${JSON.stringify(`${options.kind}.initialized`)},`,
      '      actor: "System",',
      `      action: ${JSON.stringify(`${options.kind} module initialized`)},`,
      '      status: "success",',
      `      details: { module: ${JSON.stringify(name)} },`,
      "    });",
    ] : []),
    "    return {",
    ...(required.length ? required.map(method) : ["      // declare seus exports aqui"]),
    "    };", "  },", "});", "",
  ].join("\n");
  const types = [
    'import type { InferModuleAPI } from "@gravewright/sdk";',
    'import module from "./index.js";', "",
    `export type ${interfaceName} = InferModuleAPI<typeof module>;`, "",
    'declare module "@gravewright/sdk" {',
    "  interface ModuleRegistry {",
    `    ${JSON.stringify(name)}: ${interfaceName};`,
    "  }", "}", "",
  ].join("\n");
  const files = new Map<string, string>([["manifest.json", `${JSON.stringify(manifest, null, 2)}\n`], ["index.ts", index], ["types.ts", types]]);
  if (options.complete) {
    files.set("README.md", `# ${name}\n\nComplete ${options.kind} example generated by Gravewright.\n\nThe module starts disabled. Review it, run \`grave doctor\`, then activate it explicitly.\n`);
    files.set("index.test.ts", `import test from "node:test";\nimport assert from "node:assert/strict";\n\ntest(${JSON.stringify(`${name} scaffold`)}, () => {\n  assert.ok(true);\n});\n`);
  }
  if (!options.dryRun) {
    await mkdir(directory, { recursive: true });
    await Promise.all([...files].map(([file, content]) => writeFile(path.join(directory, file), content, { flag: "wx" })));
  }
  return { directory, files: [...files.keys()] };
}
