const fs=require("fs"),vm=require("vm"),assert=require("assert");
function environment(context={}){
  const listeners=new Map(),frames=new Map();let frame=0,now=100000,reloads=0;
  class Audio{constructor(src){this.src=src;this.volume=1;this.paused=true;}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
  const canvas={dataset:{sceneId:"a",roomId:"r"}};
  const document={activeElement:null,addEventListener:(n,f)=>listeners.set(n,f),dispatchEvent:event=>listeners.get(event.type)?.(event),querySelector:selector=>selector.includes("data-map-canvas")?canvas:null,getElementById:()=>({textContent:JSON.stringify(context)})};
  class CustomEvent{constructor(type,options={}){this.type=type;this.detail=options.detail;}}
  const sandbox={console,Audio,CustomEvent,CSS:{escape:value=>value},document,localStorage:{getItem:()=>"0.5"},performance:{now:()=>now},Date:{now:()=>now},addEventListener:(n,f)=>listeners.set(n,f),requestAnimationFrame:f=>{frames.set(++frame,f);return frame;},cancelAnimationFrame:id=>frames.delete(id),window:{location:{reload:()=>reloads++}},setTimeout,clearTimeout,setInterval:()=>1,clearInterval:()=>{}};sandbox.window.window=sandbox.window;sandbox.window.document=document;sandbox.window.setTimeout=setTimeout;sandbox.window.clearTimeout=clearTimeout;sandbox.window.setInterval=sandbox.setInterval;sandbox.window.clearInterval=sandbox.clearInterval;
  vm.createContext(sandbox);return{sandbox,listeners,advance(ms){now+=ms;for(const [id,fn] of [...frames]){frames.delete(id);fn();}},reloads:()=>reloads};
}
async function audio(){const e=environment();vm.runInContext(fs.readFileSync("static/js/audio/core-audio-runtime.js","utf8"),e.sandbox);const api=e.sandbox.window.GravewrightAudioRuntime;await api.unlock();await api.project({id:"a",asset:{kind:"library-asset",id:"x"},channel:"music",state:"playing",loop:true,gain:.8,startedAt:100,updatedAt:100000,ownerPackageId:"core",fade:{durationMs:2000,curve:"linear",direction:"in",startedAt:100000,fromGain:0}});assert.equal(api.inspect("a").volume,0);e.advance(1000);assert(Math.abs(api.inspect("a").volume-.2)<.001);e.advance(1000);assert(Math.abs(api.inspect("a").volume-.4)<.001);await api.project({id:"a",asset:{kind:"library-asset",id:"x"},channel:"music",state:"playing",loop:true,gain:.8,ownerPackageId:"core",fade:{durationMs:1000,curve:"linear",direction:"out",startedAt:102000,fromGain:.8}});e.advance(1000);assert.equal(api.inspect("a"),null);assert.equal(e.sandbox.localStorage.getItem("gravewright.audio.volume.music"),"0.5");}
function input(){const e=environment({inputBindings:[]});vm.runInContext(fs.readFileSync("static/js/input/core-input-runtime.js","utf8"),e.sandbox);const api=e.sandbox.window.GravewrightInputRuntime;let hits=0;api.registerCommand("pkg",{id:"go",contexts:["text-input-excluded"],defaultBindings:["Shift+H"]},()=>hits++);e.listeners.get("keydown")({key:"H",shiftKey:true,ctrlKey:false,altKey:false,metaKey:false,preventDefault(){}});assert.equal(hits,1);api.updateBinding("pkg","go","Ctrl+J");e.listeners.get("keydown")({key:"H",shiftKey:true,ctrlKey:false,altKey:false,metaKey:false,preventDefault(){}});e.listeners.get("keydown")({key:"J",shiftKey:false,ctrlKey:true,altKey:false,metaKey:false,preventDefault(){}});assert.equal(hits,2);e.sandbox.document.activeElement={matches:()=>true,isContentEditable:false};e.listeners.get("keydown")({key:"J",shiftKey:false,ctrlKey:true,altKey:false,metaKey:false,preventDefault(){}});assert.equal(hits,2);}
async function navigation(){const e=environment({scene:{id:"a"},room:{id:"r"}});e.sandbox.window.GravewrightMapApi={loadSceneManifest:async()=>({scene_id:"b",campaign_id:"r",width:100,height:100,tile_size:50,layers:[]})};vm.runInContext(fs.readFileSync("static/js/navigation/core-scene-navigation.js","utf8"),e.sandbox);e.listeners.get("vtt:transport-event")({detail:{event:"navigation.scene.changed",payload:{scene_id:"b",room_id:"r"}}});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(e.reloads(),0);}
(async()=>{await audio();input();await navigation();console.log("scene-runtime runtime harness: ok");})().catch(error=>{console.error(error);process.exit(1);});
