const fs=require("fs"),vm=require("vm"),assert=require("assert"),{performance}=require("perf_hooks");const listeners=new Map();let hit=null,commits=[];
const classes=()=>{const set=new Set();return{add:x=>set.add(x),remove:x=>set.delete(x),has:x=>set.has(x)}};
function node(kind,id){const n={dataset:{},classList:classes(),isConnected:true,hidden:false,getAttribute:()=>null,closest(selector){if(kind==="card"&&selector.includes("card-drag-id"))return n;if(kind==="item"&&selector.includes("item-card"))return n;if(kind==="journal"&&selector.includes("journal-card"))return n;if(kind==="object"&&selector.includes("scene-object-id"))return n;if(kind==="canvas"&&selector.includes("map-canvas"))return n;return null;}};if(kind==="card")n.dataset.cardDragId=id;if(kind==="item")n.dataset.itemCard=id;if(kind==="journal")n.dataset.journalId=id;if(kind==="object")Object.assign(n.dataset,{sceneObjectId:id,sceneObjectType:"pkg.zone",sceneObjectVersion:"1"});if(kind==="canvas")n.dataset.sceneId=id;return n;}
const document={addEventListener:(n,f)=>listeners.set(n,f),elementFromPoint:()=>hit,querySelector:()=>null};const sandbox={console,document,crypto:{randomUUID:()=>"once"},window:{GravewrightMap:{activeCanvas:()=>node("canvas","scene"),worldFromScreen:()=>({worldX:10,worldY:20})}},addEventListener:(n,f)=>listeners.set(n,f)};vm.createContext(sandbox);vm.runInContext(fs.readFileSync("static/js/input/core-semantic-pointer-host.js","utf8"),sandbox);const api=sandbox.window.GravewrightSemanticPointerHost;
const sourceDisposers={};for(const kind of ["card","item","journal"]){sourceDisposers[kind]=api.registerSource("pkg",{id:`${kind}-source`,referenceKinds:[kind]},value=>commits.push(value),"campaign");}
const targetDisposer=api.registerTarget("pkg",{id:"zone",targetKinds:["scene-object"],worldObjectTypeId:"pkg.zone",operations:["place"]});
const ev=value=>({...value,preventDefault(){}});const source=node("card","c1"),target=node("object","z1");listeners.get("pointerdown")(ev({target:source,pointerId:1,clientX:0,clientY:0}));assert(api.active());listeners.get("keydown")(ev({key:"Escape"}));assert(!api.active()&&commits.length===0);
for(const [index,kind] of ["card","item","journal"].entries()){const candidate=node(kind,`${kind}1`);listeners.get("pointerdown")(ev({target:candidate,pointerId:10+index,clientX:0,clientY:0}));hit=target;listeners.get("pointermove")({pointerId:10+index,clientX:20,clientY:20});listeners.get("pointercancel")({pointerId:10+index});assert(!api.active()&&commits.length===0);}
const gone=node("card","gone");listeners.get("pointerdown")(ev({target:gone,pointerId:20,clientX:0,clientY:0}));hit=target;listeners.get("pointermove")({pointerId:20,clientX:20,clientY:20});gone.isConnected=false;listeners.get("pointerup")({pointerId:20,clientX:20,clientY:20});assert.equal(commits.length,0);
const targetGone=node("object","target-gone");listeners.get("pointerdown")(ev({target:source,pointerId:21,clientX:0,clientY:0,pointerType:"touch"}));hit=targetGone;listeners.get("pointermove")({pointerId:21,clientX:20,clientY:20,pointerType:"touch"});targetGone.isConnected=false;listeners.get("pointerup")({pointerId:21,clientX:20,clientY:20,pointerType:"touch"});assert.equal(commits.length,0);
listeners.get("pointerdown")(ev({target:source,pointerId:22,clientX:0,clientY:0}));hit=target;listeners.get("pointermove")({pointerId:22,clientX:20,clientY:20});listeners.get("pointercancel")({pointerId:22});listeners.get("pointerup")({pointerId:22,clientX:20,clientY:20});assert.equal(commits.length,0);
const multi=node("card","multi");listeners.get("pointerdown")(ev({target:multi,pointerId:30,clientX:0,clientY:0}));listeners.get("pointerdown")(ev({target:multi,pointerId:31,clientX:0,clientY:0}));assert(!api.active());
for(const [index,name] of ["campaign.packages.changed","navigation.scene.changed","scene.deleted"].entries()){listeners.get("pointerdown")(ev({target:source,pointerId:40+index,clientX:0,clientY:0}));hit=target;listeners.get("pointermove")({pointerId:40+index,clientX:20,clientY:20});listeners.get("vtt:transport-event")({detail:{event:name}});listeners.get("pointerup")({pointerId:40+index,clientX:20,clientY:20});assert.equal(commits.length,0);}
listeners.get("pointerdown")(ev({target:source,pointerId:50,clientX:0,clientY:0}));hit=target;listeners.get("pointermove")({pointerId:50,clientX:20,clientY:20});targetDisposer();listeners.get("pointerup")({pointerId:50,clientX:20,clientY:20});assert.equal(commits.length,0);
api.registerTarget("pkg",{id:"zone",targetKinds:["scene-object"],worldObjectTypeId:"pkg.zone",operations:["place"]});
for(const [pointerId,pointerType] of [[60,"touch"],[61,"pen"]]){listeners.get("pointerdown")(ev({target:source,pointerId,clientX:0,clientY:0,pointerType}));hit=target;listeners.get("pointermove")({pointerId,clientX:20,clientY:20,pointerType});listeners.get("pointerup")({pointerId,clientX:20,clientY:20,pointerType});}
setImmediate(()=>{
  assert.equal(commits.length,2);assert(commits.every(value=>value.payload.reference==="grave://campaign/campaign/card/c1"));
  const listenerCount=listeners.size,benchmarkSource=node("item","benchmark");sourceDisposers.item();api.registerSource("benchmark",{id:"item-source",referenceKinds:["item"]},value=>commits.push(value),"isolated-campaign");
  for(let index=0;index<1000;index++)api.registerTarget("benchmark",{id:`candidate-${index}`,targetKinds:["scene-object"],worldObjectTypeId:`benchmark.type-${index}`,operations:["place"]});
  const benchmarkTarget=node("object","candidate");benchmarkTarget.dataset.sceneObjectType="benchmark.type-999";const start=performance.now();listeners.get("pointerdown")(ev({target:benchmarkSource,pointerId:70,clientX:0,clientY:0}));hit=benchmarkTarget;for(let index=0;index<100;index++)listeners.get("pointermove")({pointerId:70,clientX:20+index,clientY:20});const elapsed=performance.now()-start;
  assert.equal(commits.length,2);assert.equal(listeners.size,listenerCount);listeners.get("pointerup")({pointerId:70,clientX:120,clientY:20});setImmediate(()=>{assert.equal(commits.length,3);assert.equal(commits[2].payload.reference,"grave://campaign/isolated-campaign/item/benchmark");assert(elapsed<1000);console.log(`semantic pointer benchmark: 1000 candidates, 100 moves, ${elapsed.toFixed(2)}ms, ${listenerCount} listeners`);console.log("semantic pointer host harness: ok");});
});
