# Generated by Django 6.1.1 on 2026-09-10 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        ('gravewright_maps', '0005_tile_byte_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('back', models.FileField(blank=True, upload_to='cards/backs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('front', models.FileField(blank=True, upload_to='cards/fronts/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('zone', models.CharField(default='draw', max_length=8)),
                ('revealed', models.BooleanField(default=False)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('rotation', models.FloatField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_maps.scene')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='gravewright_cards.deck')),
            ],
        ),
    ]
