# Generated by Django 6.1.1 on 2026-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_cards', '0003_alter_cardasset_uploader_alter_deckdefinition_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scale',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
    ]
