# Generated by Django 6.1.1 on 2026-09-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_maps', '0005_tile_byte_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravewright_maps.scene')),
                ('active', models.BooleanField(default=False)),
                ('round', models.PositiveIntegerField(default=0)),
                ('turn', models.PositiveIntegerField(default=0)),
                ('combatants', models.JSONField(default=list)),
                ('history', models.JSONField(default=list)),
                ('config', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
