"""Initial portable schema (deterministic baseline).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-06

This baseline is a *static* rendering of the schema. It intentionally does NOT
import `app.persistence.tables.metadata` to build the schema, so the result of
this revision no longer changes when `tables.py` changes. Any later schema
change must ship as its own numbered Alembic revision. See
docs/adr/ADR-migration-baseline.md and tests/unit/test_schema_alembic_parity.py.

The ops below were generated once with Alembic autogenerate against the frozen
metadata and are now hand-owned; do not regenerate in place.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def _create_active_scene_index(dialect_name: str) -> None:
    # Partial unique index (one active scene per campaign). Not expressible in
    # portable metadata, so it lives here and in the parity reference build.
    if dialect_name in {"sqlite", "postgresql"}:
        op.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_scenes_active_campaign "
            "ON scenes (campaign_id) WHERE active = 1"
        )


def _drop_active_scene_index(dialect_name: str) -> None:
    if dialect_name in {"sqlite", "postgresql"}:
        op.execute("DROP INDEX IF EXISTS idx_scenes_active_campaign")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=191), nullable=False),
        sa.Column("attempt_key", sa.String(length=191), nullable=False),
        sa.Column("success", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_attempts")),
    )
    op.create_index(
        "idx_auth_attempts_action_key_created",
        "auth_attempts",
        ["action", "attempt_key", "created_at"],
        unique=False,
    )
    op.create_table(
        "package_settings",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("package_id", sa.String(length=64), nullable=False),
        sa.Column(
            "campaign_id", sa.String(length=64), server_default=sa.text("('')"), nullable=False
        ),
        sa.Column("user_id", sa.String(length=64), server_default=sa.text("('')"), nullable=False),
        sa.Column("setting_key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_settings")),
        sa.UniqueConstraint(
            "package_id",
            "campaign_id",
            "user_id",
            "setting_key",
            name=op.f("uq_package_settings_package_id_campaign_id_user_id_setting_key"),
        ),
    )
    op.create_index(
        "idx_package_settings_campaign", "package_settings", ["campaign_id"], unique=False
    )
    op.create_index(
        "idx_package_settings_package", "package_settings", ["package_id"], unique=False
    )
    op.create_table(
        "schema_migrations",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("applied_at", sa.String(length=191), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_migrations")),
    )
    op.create_table(
        "session_store",
        sa.Column("key", sa.String(length=191), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_session_store")),
    )
    op.create_index("idx_session_store_user_id", "session_store", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("email", sa.String(length=191), nullable=False),
        sa.Column("password_hash", sa.String(length=191), nullable=False),
        sa.Column("system_role", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=191), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("active_system_id", sa.String(length=191), nullable=True),
        sa.Column("initial_state_json", sa.Text(), nullable=False),
        sa.Column("persistent_state_json", sa.Text(), nullable=False),
        sa.Column("state_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_campaigns_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index("idx_campaigns_owner_user_id", "campaigns", ["owner_user_id"], unique=False)
    op.create_table(
        "installed_packages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), server_default=sa.text("('')"), nullable=False),
        sa.Column("version", sa.String(length=191), server_default=sa.text("('')"), nullable=False),
        sa.Column(
            "status", sa.String(length=191), server_default=sa.text("'installed'"), nullable=False
        ),
        sa.Column("package_dir", sa.Text(), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column(
            "compatibility_status",
            sa.String(length=191),
            server_default=sa.text("'unverified'"),
            nullable=False,
        ),
        sa.Column("validation_errors_json", sa.Text(), nullable=False),
        sa.Column("package_sha256", sa.String(length=64), nullable=True),
        sa.Column("manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("last_validated_at", sa.Integer(), nullable=True),
        sa.Column("last_validation_status", sa.String(length=191), nullable=True),
        sa.Column("installed_by_user_id", sa.String(length=64), nullable=True),
        sa.Column("installed_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("enabled_at", sa.Integer(), nullable=True),
        sa.Column("disabled_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["installed_by_user_id"],
            ["users.id"],
            name=op.f("fk_installed_packages_installed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installed_packages")),
    )
    op.create_index("idx_installed_packages_kind", "installed_packages", ["kind"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("used_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_reset_tokens_token_hash")),
    )
    op.create_index(
        "idx_password_reset_tokens_expires_at",
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "idx_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "game_layout_mode",
            sa.String(length=191),
            server_default=sa.text("'gravewright'"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "user_presence",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_presence_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_presence")),
    )
    op.create_index(
        "idx_user_presence_last_seen_at", "user_presence", ["last_seen_at"], unique=False
    )
    op.create_table(
        "actor_folders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=191), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_actor_folders_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_actor_folders_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actor_folders")),
    )
    op.create_index("idx_actor_folders_campaign_id", "actor_folders", ["campaign_id"], unique=False)
    op.create_table(
        "actors_core",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("system_id", sa.String(length=191), nullable=False),
        sa.Column("type", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("folder_id", sa.String(length=64), nullable=True),
        sa.Column("portrait_asset_id", sa.String(length=64), nullable=True),
        sa.Column("token_asset_id", sa.String(length=64), nullable=True),
        sa.Column("default_token_config_json", sa.Text(), nullable=True),
        sa.Column("permissions_json", sa.Text(), nullable=False),
        sa.Column("external_data_ref", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=191), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_actors_core_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_actors_core_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors_core")),
    )
    op.create_index(
        "idx_actors_core_campaign", "actors_core", ["campaign_id", "status"], unique=False
    )
    op.create_index(
        "idx_actors_core_campaign_system", "actors_core", ["campaign_id", "system_id"], unique=False
    )
    op.create_table(
        "asset_folders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_asset_folders_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_folders")),
    )
    op.create_index(
        "idx_asset_folders_campaign_parent",
        "asset_folders",
        ["campaign_id", "parent_id", "sort_order", "name"],
        unique=False,
    )
    op.create_table(
        "campaign_delete_codes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("used_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_delete_codes_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_campaign_delete_codes_requested_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_delete_codes")),
    )
    op.create_index(
        "idx_campaign_delete_codes_campaign_id",
        "campaign_delete_codes",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        "idx_campaign_delete_codes_expires_at",
        "campaign_delete_codes",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "campaign_invitations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("invited_user_id", sa.String(length=64), nullable=False),
        sa.Column("invited_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=191), nullable=False),
        sa.Column("status", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("responded_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_invitations_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_campaign_invitations_invited_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["users.id"],
            name=op.f("fk_campaign_invitations_invited_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_invitations")),
    )
    op.create_index(
        "idx_campaign_invitations_campaign_status",
        "campaign_invitations",
        ["campaign_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_campaign_invitations_invited_by",
        "campaign_invitations",
        ["invited_by_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_campaign_invitations_invited_user_status",
        "campaign_invitations",
        ["invited_user_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "campaign_members",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_members_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_campaign_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_members")),
        sa.UniqueConstraint(
            "campaign_id", "user_id", name=op.f("uq_campaign_members_campaign_id_user_id")
        ),
    )
    op.create_index(
        "idx_campaign_members_campaign_id", "campaign_members", ["campaign_id"], unique=False
    )
    op.create_index("idx_campaign_members_user_id", "campaign_members", ["user_id"], unique=False)
    op.create_table(
        "campaign_packages",
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("package_id", sa.String(length=64), nullable=False),
        sa.Column("activation_role", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=191), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("load_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("enabled_by_user_id", sa.String(length=64), nullable=True),
        sa.Column("enabled_at", sa.Integer(), nullable=False),
        sa.Column("disabled_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_packages_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["enabled_by_user_id"],
            ["users.id"],
            name=op.f("fk_campaign_packages_enabled_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["installed_packages.id"],
            name=op.f("fk_campaign_packages_package_id_installed_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("campaign_id", "package_id", name=op.f("pk_campaign_packages")),
    )
    op.create_index(
        "idx_campaign_packages_campaign", "campaign_packages", ["campaign_id"], unique=False
    )
    op.create_index(
        "idx_campaign_packages_role",
        "campaign_packages",
        ["campaign_id", "activation_role"],
        unique=False,
    )
    op.create_table(
        "campaign_permission_overrides",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=191), nullable=False),
        sa.Column("subject_id", sa.String(length=191), nullable=False),
        sa.Column("permission_key", sa.String(length=191), nullable=False),
        sa.Column("effect", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_permission_overrides_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_permission_overrides")),
        sa.UniqueConstraint(
            "campaign_id",
            "subject_type",
            "subject_id",
            "permission_key",
            name=op.f(
                "uq_campaign_permission_overrides_campaign_id_subject_type_subject_id_permission_key"
            ),
        ),
    )
    op.create_index(
        "idx_campaign_permission_overrides_campaign_subject",
        "campaign_permission_overrides",
        ["campaign_id", "subject_type", "subject_id"],
        unique=False,
    )
    op.create_index(
        "idx_campaign_permission_overrides_permission",
        "campaign_permission_overrides",
        ["permission_key"],
        unique=False,
    )
    op.create_table(
        "campaign_presence",
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("is_online", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_presence_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_campaign_presence_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("campaign_id", "user_id", name=op.f("pk_campaign_presence")),
    )
    op.create_index(
        "idx_campaign_presence_campaign_online",
        "campaign_presence",
        ["campaign_id", "is_online", "last_seen_at"],
        unique=False,
    )
    op.create_index("idx_campaign_presence_user", "campaign_presence", ["user_id"], unique=False)
    op.create_table(
        "campaign_system_history",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("previous_system_id", sa.String(length=191), nullable=True),
        sa.Column("next_system_id", sa.String(length=191), nullable=True),
        sa.Column("changed_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_system_history_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_campaign_system_history_changed_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_system_history")),
    )
    op.create_index(
        "idx_campaign_system_history_campaign_id",
        "campaign_system_history",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "card_deck_definitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=True),
        sa.Column("package_id", sa.String(length=64), nullable=True),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("scope", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_back_asset_id", sa.String(length=64), nullable=True),
        sa.Column("editable", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_card_deck_definitions_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_card_deck_definitions_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_deck_definitions")),
    )
    op.create_index(
        "idx_card_deck_definitions_campaign", "card_deck_definitions", ["campaign_id"], unique=False
    )
    op.create_index(
        "idx_card_deck_definitions_owner", "card_deck_definitions", ["owner_user_id"], unique=False
    )
    op.create_index(
        "idx_card_deck_definitions_package", "card_deck_definitions", ["package_id"], unique=False
    )
    op.create_index(
        "idx_card_deck_definitions_scope", "card_deck_definitions", ["scope"], unique=False
    )
    op.create_table(
        "card_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("actor_user_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=191), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_card_events_actor_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_card_events_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["campaigns.id"],
            name=op.f("fk_card_events_room_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_events")),
    )
    op.create_index(
        "idx_card_events_campaign", "card_events", ["campaign_id", "created_at"], unique=False
    )
    op.create_index("idx_card_events_type", "card_events", ["event_type"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("author_user_id", sa.String(length=64), nullable=False),
        sa.Column("author_name", sa.String(length=191), nullable=False),
        sa.Column("author_role", sa.String(length=191), nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("expression", sa.Text(), nullable=True),
        sa.Column("groups_json", sa.Text(), nullable=True),
        sa.Column("modifier", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("visibility", sa.String(length=191), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_chat_messages_author_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_chat_messages_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        "idx_chat_messages_campaign_created",
        "chat_messages",
        ["campaign_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "combat_encounters",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status", sa.String(length=191), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "mode", sa.String(length=191), server_default=sa.text("'manual'"), nullable=False
        ),
        sa.Column(
            "strategy", sa.String(length=191), server_default=sa.text("'manual'"), nullable=False
        ),
        sa.Column("round_number", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("turn_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "phase", sa.String(length=191), server_default=sa.text("'combat.start'"), nullable=False
        ),
        sa.Column("settings_json", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("ended_at", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_combat_encounters_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_combat_encounters")),
    )
    op.create_index(
        "idx_combat_encounters_campaign_status",
        "combat_encounters",
        ["campaign_id", "status"],
        unique=False,
    )
    op.create_table(
        "item_folders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=191), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_item_folders_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_item_folders_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_folders")),
    )
    op.create_index("idx_item_folders_campaign_id", "item_folders", ["campaign_id"], unique=False)
    op.create_table(
        "items_core",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("system_id", sa.String(length=191), nullable=False),
        sa.Column("type", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("folder_id", sa.String(length=64), nullable=True),
        sa.Column("portrait_asset_id", sa.String(length=64), nullable=True),
        sa.Column("permissions_json", sa.Text(), nullable=False),
        sa.Column("external_data_ref", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=191), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_items_core_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_items_core_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items_core")),
    )
    op.create_index(
        "idx_items_core_campaign", "items_core", ["campaign_id", "status"], unique=False
    )
    op.create_index(
        "idx_items_core_campaign_system", "items_core", ["campaign_id", "system_id"], unique=False
    )
    op.create_table(
        "journal_folders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=191), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_journal_folders_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_journal_folders_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_folders")),
    )
    op.create_index(
        "idx_journal_folders_campaign_id", "journal_folders", ["campaign_id"], unique=False
    )
    op.create_table(
        "library_assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("folder_id", sa.String(length=64), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=191), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_library_assets_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_library_assets_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_assets")),
    )
    op.create_index(
        "idx_library_assets_campaign", "library_assets", ["campaign_id", "created_at"], unique=False
    )
    op.create_index(
        "idx_library_assets_folder", "library_assets", ["campaign_id", "folder_id"], unique=False
    )
    op.create_table(
        "package_content_imports",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("package_id", sa.String(length=64), nullable=False),
        sa.Column("content_pack_id", sa.String(length=191), nullable=False),
        sa.Column("content_pack_type", sa.String(length=191), nullable=False),
        sa.Column("imported_by_user_id", sa.String(length=64), nullable=True),
        sa.Column("imported_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_package_content_imports_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["imported_by_user_id"],
            ["users.id"],
            name=op.f("fk_package_content_imports_imported_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_content_imports")),
    )
    op.create_index(
        "idx_package_content_imports_campaign",
        "package_content_imports",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        "idx_package_content_imports_package",
        "package_content_imports",
        ["package_id"],
        unique=False,
    )
    op.create_table(
        "room_event_log",
        sa.Column(
            "seq",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=191), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["campaigns.id"],
            name=op.f("fk_room_event_log_room_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_room_event_log")),
        sa.UniqueConstraint("id", name=op.f("uq_room_event_log_id")),
    )
    op.create_index("idx_room_event_log_expires_at", "room_event_log", ["expires_at"], unique=False)
    op.create_index(
        "idx_room_event_log_room_seq", "room_event_log", ["room_id", "seq"], unique=False
    )
    op.create_table(
        "scene_groups",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column(
            "color", sa.String(length=191), server_default=sa.text("'#8ea8ff'"), nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_scene_groups_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_groups")),
    )
    op.create_index(
        "idx_scene_groups_campaign_order",
        "scene_groups",
        ["campaign_id", "sort_order", "created_at"],
        unique=False,
    )
    op.create_table(
        "streamer_links",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("token", sa.String(length=191), nullable=False),
        sa.Column("guest_user_id", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_streamer_links_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_streamer_links_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["guest_user_id"],
            ["users.id"],
            name=op.f("fk_streamer_links_guest_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streamer_links")),
        sa.UniqueConstraint("token", name=op.f("uq_streamer_links_token")),
    )
    op.create_index("idx_streamer_links_campaign", "streamer_links", ["campaign_id"], unique=False)
    op.create_index("idx_streamer_links_token", "streamer_links", ["token"], unique=False)
    op.create_table(
        "transport_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("target_user_id", sa.String(length=64), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("event", sa.String(length=191), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["campaigns.id"],
            name=op.f("fk_transport_messages_room_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("fk_transport_messages_target_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transport_messages")),
    )
    op.create_index("idx_transport_messages_event", "transport_messages", ["event"], unique=False)
    op.create_index(
        "idx_transport_messages_expires_at", "transport_messages", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_transport_messages_room_id", "transport_messages", ["room_id"], unique=False
    )
    op.create_index(
        "idx_transport_messages_target_user_pending",
        "transport_messages",
        ["target_user_id", "consumed_at", "expires_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "actor_owners",
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors_core.id"],
            name=op.f("fk_actor_owners_actor_id_actors_core"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_actor_owners_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("actor_id", "user_id", name=op.f("pk_actor_owners")),
    )
    op.create_index("idx_actor_owners_user_id", "actor_owners", ["user_id"], unique=False)
    op.create_table(
        "actor_permissions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("can_view", sa.Integer(), nullable=False),
        sa.Column("can_edit", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors_core.id"],
            name=op.f("fk_actor_permissions_actor_id_actors_core"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_actor_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actor_permissions")),
        sa.UniqueConstraint(
            "actor_id", "user_id", name=op.f("uq_actor_permissions_actor_id_user_id")
        ),
    )
    op.create_index(
        "idx_actor_permissions_actor_id", "actor_permissions", ["actor_id"], unique=False
    )
    op.create_index("idx_actor_permissions_user_id", "actor_permissions", ["user_id"], unique=False)
    op.create_table(
        "card_deck_instances",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("deck_definition_id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("active", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_card_deck_instances_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deck_definition_id"],
            ["card_deck_definitions.id"],
            name=op.f("fk_card_deck_instances_deck_definition_id_card_deck_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_card_deck_instances_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["campaigns.id"],
            name=op.f("fk_card_deck_instances_room_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_deck_instances")),
    )
    op.create_index(
        "idx_card_deck_instances_campaign", "card_deck_instances", ["campaign_id"], unique=False
    )
    op.create_index(
        "idx_card_deck_instances_definition",
        "card_deck_instances",
        ["deck_definition_id"],
        unique=False,
    )
    op.create_table(
        "card_definitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("deck_definition_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("subtitle", sa.String(length=191), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("front_asset_id", sa.String(length=64), nullable=False),
        sa.Column("back_asset_id", sa.String(length=64), nullable=True),
        sa.Column("tags_json", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("sort_key", sa.String(length=191), nullable=True),
        sa.Column("quantity", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_definition_id"],
            ["card_deck_definitions.id"],
            name=op.f("fk_card_definitions_deck_definition_id_card_deck_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_definitions")),
    )
    op.create_index(
        "idx_card_definitions_deck", "card_definitions", ["deck_definition_id"], unique=False
    )
    op.create_table(
        "combat_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("combat_id", sa.String(length=64), nullable=False),
        sa.Column("round_number", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("turn_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("participant_id", sa.String(length=64), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=191), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["combat_id"],
            ["combat_encounters.id"],
            name=op.f("fk_combat_events_combat_id_combat_encounters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_combat_events")),
    )
    op.create_index(
        "idx_combat_events_combat", "combat_events", ["combat_id", "created_at"], unique=False
    )
    op.create_table(
        "combat_participants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("combat_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("token_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column(
            "initiative_label",
            sa.String(length=191),
            server_default=sa.text("('')"),
            nullable=False,
        ),
        sa.Column("initiative_value", sa.Float(), nullable=True),
        sa.Column("initiative_data_json", sa.Text(), nullable=False),
        sa.Column("sort_key", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("group_key", sa.String(length=191), nullable=True),
        sa.Column("visible_to_players", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("defeated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors_core.id"],
            name=op.f("fk_combat_participants_actor_id_actors_core"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["combat_id"],
            ["combat_encounters.id"],
            name=op.f("fk_combat_participants_combat_id_combat_encounters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_combat_participants")),
    )
    op.create_index(
        "idx_combat_participants_combat",
        "combat_participants",
        ["combat_id", "sort_key"],
        unique=False,
    )
    op.create_table(
        "item_owners",
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items_core.id"],
            name=op.f("fk_item_owners_item_id_items_core"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_item_owners_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("item_id", "user_id", name=op.f("pk_item_owners")),
    )
    op.create_index("idx_item_owners_user_id", "item_owners", ["user_id"], unique=False)
    op.create_table(
        "item_permissions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("can_view", sa.Integer(), nullable=False),
        sa.Column("can_edit", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items_core.id"],
            name=op.f("fk_item_permissions_item_id_items_core"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_item_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_permissions")),
        sa.UniqueConstraint("item_id", "user_id", name=op.f("uq_item_permissions_item_id_user_id")),
    )
    op.create_index("idx_item_permissions_item_id", "item_permissions", ["item_id"], unique=False)
    op.create_index("idx_item_permissions_user_id", "item_permissions", ["user_id"], unique=False)
    op.create_table(
        "journals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("folder_id", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=191), nullable=False),
        sa.Column("title", sa.String(length=191), nullable=False),
        sa.Column(
            "visibility", sa.String(length=191), server_default=sa.text("'private'"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column(
            "quest_provider", sa.String(length=191), server_default=sa.text("('')"), nullable=False
        ),
        sa.Column("quest_reward", sa.Text(), nullable=False),
        sa.Column(
            "quest_progress_current", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("quest_progress_max", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status", sa.String(length=191), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_journals_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_journals_created_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["journal_folders.id"],
            name=op.f("fk_journals_folder_id_journal_folders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journals")),
    )
    op.create_index(
        "idx_journals_campaign_status",
        "journals",
        ["campaign_id", "status", "created_at"],
        unique=False,
    )
    op.create_index("idx_journals_folder_id", "journals", ["folder_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("group_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("status", sa.String(length=191), nullable=False),
        sa.Column(
            "visibility", sa.String(length=191), server_default=sa.text("'players'"), nullable=False
        ),
        sa.Column("active", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("tile_size", sa.Integer(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("grid_visible", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "grid_color", sa.String(length=191), server_default=sa.text("'#6fddb4'"), nullable=False
        ),
        sa.Column("grid_opacity", sa.Float(), server_default=sa.text("(0.4)"), nullable=False),
        sa.Column("image_scale", sa.Float(), server_default=sa.text("(1.0)"), nullable=False),
        sa.Column("start_world_x", sa.Float(), server_default=sa.text("(0.0)"), nullable=False),
        sa.Column("start_world_y", sa.Float(), server_default=sa.text("(0.0)"), nullable=False),
        sa.Column("start_zoom", sa.Float(), server_default=sa.text("(1.0)"), nullable=False),
        sa.Column("tile_table_version", sa.Integer(), nullable=False),
        sa.Column("scene_epoch", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("fog_enabled", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fog_mask", sa.LargeBinary(), nullable=True),
        sa.Column(
            "fog_baseline",
            sa.String(length=191),
            server_default=sa.text("'hide_all'"),
            nullable=False,
        ),
        sa.Column("fog_ops_json", sa.Text(), nullable=False),
        sa.Column("fog_version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("board_area_markers_json", sa.Text(), nullable=False),
        sa.Column("board_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_scenes_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["scene_groups.id"],
            name=op.f("fk_scenes_group_id_scene_groups"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenes")),
    )
    op.create_index("idx_scenes_campaign_id", "scenes", ["campaign_id", "created_at"], unique=False)
    op.create_index("idx_scenes_group_id", "scenes", ["group_id"], unique=False)
    op.create_table(
        "card_piles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("deck_instance_id", sa.String(length=64), nullable=True),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("visibility", sa.String(length=191), nullable=False),
        sa.Column("ordered", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_card_piles_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deck_instance_id"],
            ["card_deck_instances.id"],
            name=op.f("fk_card_piles_deck_instance_id_card_deck_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_card_piles_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_piles")),
    )
    op.create_index("idx_card_piles_campaign", "card_piles", ["campaign_id"], unique=False)
    op.create_index("idx_card_piles_deck", "card_piles", ["deck_instance_id", "kind"], unique=False)
    op.create_index("idx_card_piles_owner", "card_piles", ["owner_user_id"], unique=False)
    op.create_table(
        "journal_assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("journal_id", sa.String(length=64), nullable=True),
        sa.Column("folder_id", sa.String(length=64), nullable=True),
        sa.Column("owner_user_id", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.String(length=191),
            server_default=sa.text("'journal_image'"),
            nullable=False,
        ),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=191), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_journal_assets_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
            name=op.f("fk_journal_assets_journal_id_journals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_journal_assets_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_assets")),
    )
    op.create_index("idx_journal_assets_campaign", "journal_assets", ["campaign_id"], unique=False)
    op.create_index(
        "idx_journal_assets_folder", "journal_assets", ["campaign_id", "folder_id"], unique=False
    )
    op.create_index("idx_journal_assets_journal", "journal_assets", ["journal_id"], unique=False)
    op.create_table(
        "journal_owners",
        sa.Column("journal_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
            name=op.f("fk_journal_owners_journal_id_journals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_journal_owners_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("journal_id", "user_id", name=op.f("pk_journal_owners")),
    )
    op.create_index("idx_journal_owners_user_id", "journal_owners", ["user_id"], unique=False)
    op.create_table(
        "journal_permissions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("journal_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("can_view", sa.Integer(), nullable=False),
        sa.Column("can_edit", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
            name=op.f("fk_journal_permissions_journal_id_journals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_journal_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_permissions")),
        sa.UniqueConstraint(
            "journal_id", "user_id", name=op.f("uq_journal_permissions_journal_id_user_id")
        ),
    )
    op.create_index(
        "idx_journal_permissions_journal_id", "journal_permissions", ["journal_id"], unique=False
    )
    op.create_index(
        "idx_journal_permissions_user_id", "journal_permissions", ["user_id"], unique=False
    )
    op.create_table(
        "quest_board_entries",
        sa.Column("board_id", sa.String(length=64), nullable=False),
        sa.Column("quest_id", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("pinned", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "visibility",
            sa.String(length=191),
            server_default=sa.text("'public_card'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["journals.id"],
            name=op.f("fk_quest_board_entries_board_id_journals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["journals.id"],
            name=op.f("fk_quest_board_entries_quest_id_journals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("board_id", "quest_id", name=op.f("pk_quest_board_entries")),
    )
    op.create_index(
        "idx_quest_board_entries_board",
        "quest_board_entries",
        ["board_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        "idx_quest_board_entries_quest", "quest_board_entries", ["quest_id"], unique=False
    )
    op.create_table(
        "scene_assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=191), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=191), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_scene_assets_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_assets")),
    )
    op.create_index(
        "idx_scene_assets_scene_kind", "scene_assets", ["scene_id", "kind"], unique=False
    )
    op.create_table(
        "scene_image_placements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("rotation", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("scale", sa.Float(), server_default=sa.text("1"), nullable=False),
        sa.Column("z_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("natural_width", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("natural_height", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("gm_only", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("layer", sa.String(length=191), server_default=sa.text("'game'"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_scene_image_placements_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_scene_image_placements_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_scene_image_placements_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_image_placements")),
    )
    op.create_index(
        "idx_scene_image_placements_campaign",
        "scene_image_placements",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        "idx_scene_image_placements_scene",
        "scene_image_placements",
        ["scene_id", "z_index"],
        unique=False,
    )
    op.create_table(
        "scene_layers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("visibility", sa.String(length=191), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("encoding", sa.String(length=191), nullable=False),
        sa.Column("tile_table_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_scene_layers_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_layers")),
    )
    op.create_index(
        "idx_scene_layers_scene_order", "scene_layers", ["scene_id", "display_order"], unique=False
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("grid_x", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("grid_y", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("width_cells", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("height_cells", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("rotation", sa.Float(), server_default=sa.text("(0.0)"), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=True),
        sa.Column("token_asset_url", sa.Text(), nullable=True),
        sa.Column("visible", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("hidden", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "disposition",
            sa.String(length=191),
            server_default=sa.text("'neutral'"),
            nullable=False,
        ),
        sa.Column(
            "actor_link_mode",
            sa.String(length=191),
            server_default=sa.text("'unlinked'"),
            nullable=False,
        ),
        sa.Column("overrides_json", sa.Text(), nullable=False),
        sa.Column("controlled_by_user_ids_json", sa.Text(), nullable=False),
        sa.Column(
            "controlled_by_role",
            sa.String(length=191),
            server_default=sa.text("'gm'"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors_core.id"],
            name=op.f("fk_tokens_actor_id_actors_core"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["scenes.id"], name=op.f("fk_tokens_scene_id_scenes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
    )
    op.create_index("idx_tokens_actor_id", "tokens", ["actor_id"], unique=False)
    op.create_index(
        "idx_tokens_scene_grid", "tokens", ["scene_id", "grid_x", "grid_y"], unique=False
    )
    op.create_index("idx_tokens_scene_id", "tokens", ["scene_id", "created_at"], unique=False)
    op.create_table(
        "card_instances",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("deck_instance_id", sa.String(length=64), nullable=False),
        sa.Column("card_definition_id", sa.String(length=64), nullable=False),
        sa.Column("current_pile_id", sa.String(length=64), nullable=True),
        sa.Column("current_scene_id", sa.String(length=64), nullable=True),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("face_state", sa.String(length=191), nullable=False),
        sa.Column("visibility", sa.String(length=191), nullable=False),
        sa.Column("locked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_card_instances_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["card_definition_id"],
            ["card_definitions.id"],
            name=op.f("fk_card_instances_card_definition_id_card_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["current_pile_id"],
            ["card_piles.id"],
            name=op.f("fk_card_instances_current_pile_id_card_piles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_scene_id"],
            ["scenes.id"],
            name=op.f("fk_card_instances_current_scene_id_scenes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deck_instance_id"],
            ["card_deck_instances.id"],
            name=op.f("fk_card_instances_deck_instance_id_card_deck_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_card_instances_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_instances")),
    )
    op.create_index("idx_card_instances_campaign", "card_instances", ["campaign_id"], unique=False)
    op.create_index("idx_card_instances_deck", "card_instances", ["deck_instance_id"], unique=False)
    op.create_index("idx_card_instances_pile", "card_instances", ["current_pile_id"], unique=False)
    op.create_table(
        "scene_chunks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("layer_id", sa.String(length=64), nullable=False),
        sa.Column("cx", sa.Integer(), nullable=False),
        sa.Column("cy", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=191), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("encoding", sa.String(length=191), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["layer_id"],
            ["scene_layers.id"],
            name=op.f("fk_scene_chunks_layer_id_scene_layers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_scene_chunks_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_chunks")),
        sa.UniqueConstraint("layer_id", "cx", "cy", name=op.f("uq_scene_chunks_layer_id_cx_cy")),
    )
    op.create_index(
        "idx_scene_chunks_scene_layer_coord",
        "scene_chunks",
        ["scene_id", "layer_id", "cx", "cy"],
        unique=False,
    )
    op.create_table(
        "scene_tiles",
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("layer_id", sa.String(length=64), nullable=False),
        sa.Column("tile_ref", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("tx", sa.Integer(), nullable=False),
        sa.Column("ty", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=191), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["scene_assets.id"],
            name=op.f("fk_scene_tiles_asset_id_scene_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["layer_id"],
            ["scene_layers.id"],
            name=op.f("fk_scene_tiles_layer_id_scene_layers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_scene_tiles_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scene_id", "layer_id", "tile_ref", name=op.f("pk_scene_tiles")),
    )
    op.create_index(
        "idx_scene_tiles_layer_coord", "scene_tiles", ["layer_id", "tx", "ty"], unique=False
    )
    op.create_table(
        "token_conditions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("token_id", sa.String(length=64), nullable=False),
        sa.Column("condition_id", sa.String(length=191), nullable=False),
        sa.Column("label", sa.String(length=191), nullable=False),
        sa.Column("icon", sa.String(length=191), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=191), nullable=True),
        sa.Column(
            "kind", sa.String(length=191), server_default=sa.text("'neutral'"), nullable=False
        ),
        sa.Column(
            "visible_to",
            sa.String(length=191),
            server_default=sa.text("'everyone'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
            name=op.f("fk_token_conditions_token_id_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_conditions")),
        sa.UniqueConstraint(
            "token_id", "condition_id", name=op.f("uq_token_conditions_token_id_condition_id")
        ),
    )
    op.create_index("idx_token_conditions_token_id", "token_conditions", ["token_id"], unique=False)
    op.create_table(
        "card_pile_entries",
        sa.Column("pile_id", sa.String(length=64), nullable=False),
        sa.Column("card_instance_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("inserted_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_instance_id"],
            ["card_instances.id"],
            name=op.f("fk_card_pile_entries_card_instance_id_card_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pile_id"],
            ["card_piles.id"],
            name=op.f("fk_card_pile_entries_pile_id_card_piles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pile_id", "card_instance_id", name=op.f("pk_card_pile_entries")),
        sa.UniqueConstraint("card_instance_id", name=op.f("uq_card_pile_entries_card_instance_id")),
        sa.UniqueConstraint(
            "pile_id", "position", name=op.f("uq_card_pile_entries_pile_id_position")
        ),
    )
    op.create_index(
        "idx_card_pile_entries_pile_order",
        "card_pile_entries",
        ["pile_id", "position"],
        unique=False,
    )
    op.create_table(
        "scene_card_placements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("card_instance_id", sa.String(length=64), nullable=False),
        sa.Column("owner_user_id", sa.String(length=64), nullable=True),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("rotation", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("scale", sa.Float(), server_default=sa.text("1"), nullable=False),
        sa.Column("z_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("face_state", sa.String(length=191), nullable=False),
        sa.Column("visibility", sa.String(length=191), nullable=False),
        sa.Column("locked", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_scene_card_placements_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["card_instance_id"],
            ["card_instances.id"],
            name=op.f("fk_scene_card_placements_card_instance_id_card_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_scene_card_placements_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_scene_card_placements_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_card_placements")),
        sa.UniqueConstraint(
            "card_instance_id", name=op.f("uq_scene_card_placements_card_instance_id")
        ),
    )
    op.create_index(
        "idx_scene_card_placements_card",
        "scene_card_placements",
        ["card_instance_id"],
        unique=False,
    )
    op.create_index(
        "idx_scene_card_placements_scene",
        "scene_card_placements",
        ["scene_id", "z_index"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_active_scene_index(op.get_bind().dialect.name)


def downgrade() -> None:
    _drop_active_scene_index(op.get_bind().dialect.name)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_scene_card_placements_scene", table_name="scene_card_placements")
    op.drop_index("idx_scene_card_placements_card", table_name="scene_card_placements")
    op.drop_table("scene_card_placements")
    op.drop_index("idx_card_pile_entries_pile_order", table_name="card_pile_entries")
    op.drop_table("card_pile_entries")
    op.drop_index("idx_token_conditions_token_id", table_name="token_conditions")
    op.drop_table("token_conditions")
    op.drop_index("idx_scene_tiles_layer_coord", table_name="scene_tiles")
    op.drop_table("scene_tiles")
    op.drop_index("idx_scene_chunks_scene_layer_coord", table_name="scene_chunks")
    op.drop_table("scene_chunks")
    op.drop_index("idx_card_instances_pile", table_name="card_instances")
    op.drop_index("idx_card_instances_deck", table_name="card_instances")
    op.drop_index("idx_card_instances_campaign", table_name="card_instances")
    op.drop_table("card_instances")
    op.drop_index("idx_tokens_scene_id", table_name="tokens")
    op.drop_index("idx_tokens_scene_grid", table_name="tokens")
    op.drop_index("idx_tokens_actor_id", table_name="tokens")
    op.drop_table("tokens")
    op.drop_index("idx_scene_layers_scene_order", table_name="scene_layers")
    op.drop_table("scene_layers")
    op.drop_index("idx_scene_image_placements_scene", table_name="scene_image_placements")
    op.drop_index("idx_scene_image_placements_campaign", table_name="scene_image_placements")
    op.drop_table("scene_image_placements")
    op.drop_index("idx_scene_assets_scene_kind", table_name="scene_assets")
    op.drop_table("scene_assets")
    op.drop_index("idx_quest_board_entries_quest", table_name="quest_board_entries")
    op.drop_index("idx_quest_board_entries_board", table_name="quest_board_entries")
    op.drop_table("quest_board_entries")
    op.drop_index("idx_journal_permissions_user_id", table_name="journal_permissions")
    op.drop_index("idx_journal_permissions_journal_id", table_name="journal_permissions")
    op.drop_table("journal_permissions")
    op.drop_index("idx_journal_owners_user_id", table_name="journal_owners")
    op.drop_table("journal_owners")
    op.drop_index("idx_journal_assets_journal", table_name="journal_assets")
    op.drop_index("idx_journal_assets_folder", table_name="journal_assets")
    op.drop_index("idx_journal_assets_campaign", table_name="journal_assets")
    op.drop_table("journal_assets")
    op.drop_index("idx_card_piles_owner", table_name="card_piles")
    op.drop_index("idx_card_piles_deck", table_name="card_piles")
    op.drop_index("idx_card_piles_campaign", table_name="card_piles")
    op.drop_table("card_piles")
    op.drop_index("idx_scenes_group_id", table_name="scenes")
    op.drop_index("idx_scenes_campaign_id", table_name="scenes")
    op.drop_table("scenes")
    op.drop_index("idx_journals_folder_id", table_name="journals")
    op.drop_index("idx_journals_campaign_status", table_name="journals")
    op.drop_table("journals")
    op.drop_index("idx_item_permissions_user_id", table_name="item_permissions")
    op.drop_index("idx_item_permissions_item_id", table_name="item_permissions")
    op.drop_table("item_permissions")
    op.drop_index("idx_item_owners_user_id", table_name="item_owners")
    op.drop_table("item_owners")
    op.drop_index("idx_combat_participants_combat", table_name="combat_participants")
    op.drop_table("combat_participants")
    op.drop_index("idx_combat_events_combat", table_name="combat_events")
    op.drop_table("combat_events")
    op.drop_index("idx_card_definitions_deck", table_name="card_definitions")
    op.drop_table("card_definitions")
    op.drop_index("idx_card_deck_instances_definition", table_name="card_deck_instances")
    op.drop_index("idx_card_deck_instances_campaign", table_name="card_deck_instances")
    op.drop_table("card_deck_instances")
    op.drop_index("idx_actor_permissions_user_id", table_name="actor_permissions")
    op.drop_index("idx_actor_permissions_actor_id", table_name="actor_permissions")
    op.drop_table("actor_permissions")
    op.drop_index("idx_actor_owners_user_id", table_name="actor_owners")
    op.drop_table("actor_owners")
    op.drop_index("idx_transport_messages_target_user_pending", table_name="transport_messages")
    op.drop_index("idx_transport_messages_room_id", table_name="transport_messages")
    op.drop_index("idx_transport_messages_expires_at", table_name="transport_messages")
    op.drop_index("idx_transport_messages_event", table_name="transport_messages")
    op.drop_table("transport_messages")
    op.drop_index("idx_streamer_links_token", table_name="streamer_links")
    op.drop_index("idx_streamer_links_campaign", table_name="streamer_links")
    op.drop_table("streamer_links")
    op.drop_index("idx_scene_groups_campaign_order", table_name="scene_groups")
    op.drop_table("scene_groups")
    op.drop_index("idx_room_event_log_room_seq", table_name="room_event_log")
    op.drop_index("idx_room_event_log_expires_at", table_name="room_event_log")
    op.drop_table("room_event_log")
    op.drop_index("idx_package_content_imports_package", table_name="package_content_imports")
    op.drop_index("idx_package_content_imports_campaign", table_name="package_content_imports")
    op.drop_table("package_content_imports")
    op.drop_index("idx_library_assets_folder", table_name="library_assets")
    op.drop_index("idx_library_assets_campaign", table_name="library_assets")
    op.drop_table("library_assets")
    op.drop_index("idx_journal_folders_campaign_id", table_name="journal_folders")
    op.drop_table("journal_folders")
    op.drop_index("idx_items_core_campaign_system", table_name="items_core")
    op.drop_index("idx_items_core_campaign", table_name="items_core")
    op.drop_table("items_core")
    op.drop_index("idx_item_folders_campaign_id", table_name="item_folders")
    op.drop_table("item_folders")
    op.drop_index("idx_combat_encounters_campaign_status", table_name="combat_encounters")
    op.drop_table("combat_encounters")
    op.drop_index("idx_chat_messages_campaign_created", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("idx_card_events_type", table_name="card_events")
    op.drop_index("idx_card_events_campaign", table_name="card_events")
    op.drop_table("card_events")
    op.drop_index("idx_card_deck_definitions_scope", table_name="card_deck_definitions")
    op.drop_index("idx_card_deck_definitions_package", table_name="card_deck_definitions")
    op.drop_index("idx_card_deck_definitions_owner", table_name="card_deck_definitions")
    op.drop_index("idx_card_deck_definitions_campaign", table_name="card_deck_definitions")
    op.drop_table("card_deck_definitions")
    op.drop_index("idx_campaign_system_history_campaign_id", table_name="campaign_system_history")
    op.drop_table("campaign_system_history")
    op.drop_index("idx_campaign_presence_user", table_name="campaign_presence")
    op.drop_index("idx_campaign_presence_campaign_online", table_name="campaign_presence")
    op.drop_table("campaign_presence")
    op.drop_index(
        "idx_campaign_permission_overrides_permission", table_name="campaign_permission_overrides"
    )
    op.drop_index(
        "idx_campaign_permission_overrides_campaign_subject",
        table_name="campaign_permission_overrides",
    )
    op.drop_table("campaign_permission_overrides")
    op.drop_index("idx_campaign_packages_role", table_name="campaign_packages")
    op.drop_index("idx_campaign_packages_campaign", table_name="campaign_packages")
    op.drop_table("campaign_packages")
    op.drop_index("idx_campaign_members_user_id", table_name="campaign_members")
    op.drop_index("idx_campaign_members_campaign_id", table_name="campaign_members")
    op.drop_table("campaign_members")
    op.drop_index("idx_campaign_invitations_invited_user_status", table_name="campaign_invitations")
    op.drop_index("idx_campaign_invitations_invited_by", table_name="campaign_invitations")
    op.drop_index("idx_campaign_invitations_campaign_status", table_name="campaign_invitations")
    op.drop_table("campaign_invitations")
    op.drop_index("idx_campaign_delete_codes_expires_at", table_name="campaign_delete_codes")
    op.drop_index("idx_campaign_delete_codes_campaign_id", table_name="campaign_delete_codes")
    op.drop_table("campaign_delete_codes")
    op.drop_index("idx_asset_folders_campaign_parent", table_name="asset_folders")
    op.drop_table("asset_folders")
    op.drop_index("idx_actors_core_campaign_system", table_name="actors_core")
    op.drop_index("idx_actors_core_campaign", table_name="actors_core")
    op.drop_table("actors_core")
    op.drop_index("idx_actor_folders_campaign_id", table_name="actor_folders")
    op.drop_table("actor_folders")
    op.drop_index("idx_user_presence_last_seen_at", table_name="user_presence")
    op.drop_table("user_presence")
    op.drop_table("user_preferences")
    op.drop_index("idx_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.drop_index("idx_password_reset_tokens_expires_at", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index("idx_installed_packages_kind", table_name="installed_packages")
    op.drop_table("installed_packages")
    op.drop_index("idx_campaigns_owner_user_id", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("users")
    op.drop_index("idx_session_store_user_id", table_name="session_store")
    op.drop_table("session_store")
    op.drop_table("schema_migrations")
    op.drop_index("idx_package_settings_package", table_name="package_settings")
    op.drop_index("idx_package_settings_campaign", table_name="package_settings")
    op.drop_table("package_settings")
    op.drop_index("idx_auth_attempts_action_key_created", table_name="auth_attempts")
    op.drop_table("auth_attempts")
    # ### end Alembic commands ###
