import { text as gwText } from '../../../shared/config/i18n/text.js';
// Labels and shader authoring prompts from the legacy editors.
export const effectLabels = {
    get "lighting.shaders.whole_scene"() { return gwText('Entire scene'); },
    get "lighting.particles.tool"() { return gwText('Particles'); },
    get "lighting.particles.smoke"() { return gwText('Smoke'); },
    get "lighting.particles.ember"() { return gwText('Ember'); },
    get "lighting.particles.dust"() { return gwText('Dust'); },
    get "lighting.particles.arcane"() { return gwText('Arcane'); },
    get "lighting.shaders.tool"() { return gwText('Scene shader'); },
    get "lighting.shaders.editor"() { return gwText('Scene shader'); },
    get "lighting.shaders.reference"() { return gwText('Reference'); },
    get "lighting.shaders.source"() { return gwText('GLSL code'); },
    get "lighting.shaders.intensity"() { return gwText('Intensity'); },
    get "lighting.shaders.opacity"() { return gwText('Opacity'); },
    get "lighting.shaders.blend_mode"() { return gwText('Blend mode'); },
    get "lighting.shaders.blend_hint"() { return gwText('Defines how the effect blends with the map and shaders below it.'); },
    "lighting.shaders.blend.normal": "Normal",
    get "lighting.shaders.blend.multiply"() { return gwText('Multiply'); },
    get "lighting.shaders.blend.darken"() { return gwText('Darken'); },
    get "lighting.shaders.blend.lighten"() { return gwText('Lighten'); },
    get "lighting.shaders.blend.screen"() { return gwText('Screen'); },
    get "lighting.shaders.blend.add"() { return gwText('Add (glow)'); },
    get "lighting.shaders.blend.overlay"() { return gwText('Overlay'); },
    get "lighting.shaders.blend.soft_light"() { return gwText('Soft light'); },
    get "lighting.shaders.blend.hard_light"() { return gwText('Hard light'); },
    get "lighting.shaders.blend.color_dodge"() { return gwText('Color dodge'); },
    get "lighting.shaders.blend.color_burn"() { return gwText('Color burn'); },
    get "lighting.shaders.blend.difference"() { return gwText('Difference'); },
    get "lighting.shaders.blend.exclusion"() { return gwText('Exclusion'); },
    get "lighting.shaders.blend.subtract"() { return gwText('Subtract'); },
    get "lighting.shaders.rotation"() { return gwText('Rotation'); },
    get "lighting.shaders.radius"() { return gwText('Range'); },
    get "lighting.shaders.radius_hint"() { return gwText('In cells, from the origin you drag on the map. The effect is drawn inside a frame of this size and clipped by a mask. Anything outside it cannot appear. Zero = entire scene.'); },
    get "lighting.shaders.scale"() { return gwText('Scale'); },
    get "lighting.shaders.speed"() { return gwText('Speed'); },
    get "lighting.shaders.color"() { return gwText('Color'); },
    get "lighting.shaders.enabled"() { return gwText('Active'); },
    get "lighting.shaders.save"() { return gwText('Save'); },
    get "lighting.shaders.remove"() { return gwText('Remove shader'); },
    get "lighting.shaders.group.appearance"() { return gwText('Appearance'); },
    get "lighting.shaders.group.pattern"() { return gwText('Pattern and motion'); },
    get "lighting.shaders.group.area"() { return gwText('Area'); },
    get "lighting.shaders.mode_hint"() { return gwText('Shaders appear only in cinematic mode; lightweight mode uses particles for scene effects.'); },
    get "lighting.shaders.preview"() { return gwText('Validate'); },
    get "lighting.shaders.preview_final"() { return gwText('Result'); },
    get "lighting.shaders.preview_mask"() { return gwText('Mask (range and walls)'); },
    get "lighting.shaders.preview_light"() { return gwText('Light buffer'); },
    get "lighting.shaders.prompt_title"() { return gwText('AI prompt'); },
    get "lighting.shaders.prompt_failed"() { return gwText('Could not copy. Check clipboard permissions and try again.'); },
    get "lighting.shaders.prompt_copy"() { return gwText('Copy prompt'); },
    get "lighting.shaders.prompt_copied"() { return gwText('Copied'); },
    get "lighting.particles.editor"() { return gwText('Particle emitter'); },
    get "lighting.particles.kind"() { return gwText('Type'); },
    get "lighting.particles.scale"() { return gwText('Size'); },
    get "lighting.particles.density"() { return gwText('Quantity'); },
    get "lighting.particles.color"() { return gwText('Color'); },
    get "lighting.particles.enabled"() { return gwText('Active'); },
    get "lighting.particles.remove"() { return gwText('Delete emitter'); },
    get "lighting.particles.density_hint"() { return gwText('Quantity controls performance: lower it if the scene slows down.'); },
    get "lighting.particles.hint"() { return gwText('Scene effect: does not emit light.'); },
    get "lighting.shaders.presets.title"() { return gwText('Preset library (50)'); },
    get "lighting.shaders.presets.hint"() { return gwText('Choose a preset. Applying it replaces the code and adjusts this shader\'s controls.'); },
    get "lighting.shaders.presets.search"() { return gwText('Search presets...'); },
    get "lighting.shaders.presets.category"() { return gwText('Category'); },
    get "lighting.shaders.presets.all"() { return gwText('All categories'); },
    get "lighting.shaders.presets.apply"() { return gwText('Apply preset'); },
    get "lighting.shaders.presets.applied"() { return gwText('Preset applied and saved.'); },
    get "lighting.shaders.presets.empty"() { return gwText('No preset found.'); },
    "lighting.shaders.picker.title": "Shaders",
    "lighting.shaders.picker.custom": "Custom",
    get "lighting.shaders.picker.loading"() { return gwText('Loading presets...'); },
    get "lighting.shaders.picker.error"() { return gwText('Could not load presets.'); },
    get "lighting.particles.rain"() { return gwText('Rain'); },
    get "lighting.particles.snow"() { return gwText('Snow'); },
    get "lighting.particles.firefly"() { return gwText('Fireflies'); },
    get "lighting.particles.leaves"() { return gwText('Leaves'); },
    get "lighting.particles.bubbles"() { return gwText('Bubbles'); },
    get "lighting.particles.ash"() { return gwText('Ash'); },
    get "lighting.particles.blood"() { return gwText('Blood'); },
    get "lighting.particles.runes"() { return gwText('Runes'); }
};
