version = 2

[core]
id = "gravewright"
name = "Gravewright"
enabled = true
repository = "https://github.com/Gravewright/gravewright"
releases = "https://api.github.com/repos/Gravewright/gravewright/releases?per_page=30"

[core.channels.dev]
enabled = true

[[packages]]
id = "dnd5e"
name = "D&D 5e SRD"
kind = "ruleset"
enabled = true
update_policy = "publisher"
source = "community"

[packages.channels.dev]
manifest = "https://raw.githubusercontent.com/Gravewright/gravewright-5e-srd/main/manifest.json"

[[packages]]
id = "savage-worlds"
name = "Savage Worlds"
kind = "ruleset"
enabled = true
update_policy = "publisher"
source = "community"

[packages.channels.dev]
manifest = "https://raw.githubusercontent.com/Gravewright/Savage-Worlds-Compatibility-Package-for-Gravewright/main/manifest.json"

[[packages]]
id = "gravewright-3d-dice"
name = "Gravewright 3D Dice"
kind = "addon"
enabled = true
update_policy = "publisher"
source = "community"

[packages.channels.dev]
manifest = "https://raw.githubusercontent.com/Gravewright/gravewright-3d-dice/main/manifest.json"
