import assert from 'node:assert/strict';
import { routeMeasurements, routeLengths, routePosition, MAX_ROUTE_POINTS, ROUTE_CELLS_PER_SECOND } from './token-route.js';
const token = { id: 'a', actorId: 'actor', mapId: 'scene', name: 'Hero', version: 1, linkMode: 'linked', gridX: 0, gridY: 0, cells: 1 };
const route = [[token], [{ ...token, gridX: 2 }], [{ ...token, gridX: 2, gridY: 2 }]];
const lengths = routeLengths(route);
assert.deepEqual(lengths, [2, 2]);
assert.equal(ROUTE_CELLS_PER_SECOND, 4);
assert.equal(MAX_ROUTE_POINTS, 64);
assert.equal(routePosition(route, lengths, 1).tokens[0].gridX, 1);
assert.equal(routePosition(route, lengths, 1).tokens[0].gridY, 0);
assert.equal(routePosition(route, lengths, 2).passed, 1);
assert.equal(routePosition(route, lengths, 3).tokens[0].gridX, 2);
assert.equal(routePosition(route, lengths, 3).tokens[0].gridY, 1);
assert.deepEqual(routePosition(route, lengths, 100).tokens, route[2]);
assert.ok(routePosition(route, lengths, 4).done);
const group = route.map(step => [step[0], { ...step[0], id: 'b', gridX: step[0].gridX + 3 }]);
const mid = routePosition(group, routeLengths(group), 3).tokens;
assert.equal(mid[1].gridX - mid[0].gridX, 3);
assert.equal(mid[1].gridY, mid[0].gridY);
assert.ok(routePosition([[token], [token]], [0], 0).done);
assert.deepEqual(routePosition([], [], 0).tokens, []);
const loop = [...route, [token]];
assert.deepEqual(routePosition(loop, routeLengths(loop), 100).tokens, [token]);
assert.equal(routeMeasurements(route, 5).total, 20);
assert.deepEqual(routeMeasurements(route, 5).segments.map(s => s.distance), [10, 10]);
assert.deepEqual(routeMeasurements(route, 5).segments[0], { distance: 10, x: 1.5, y: 0.5 });
assert.equal(routeMeasurements([[token], [{ ...token, gridX: 0.3, gridY: 0.4 }]], 1.5).total, 0.75);
assert.equal(routeMeasurements([[token], [{ ...token, gridX: 3, gridY: 4 }], [token]], 5).total, 50);
assert.equal(routeMeasurements(route, NaN).total, 4);
assert.equal(routeMeasurements(route, 0).total, 4);
assert.equal(routeMeasurements([], 5).total, 0);
assert.equal(routeMeasurements([[]], 5).total, 0);
// Group timing uses the longest segment; labels measure the anchor drawn on the map.
assert.equal(routeMeasurements([[token, { ...token, id: 'b' }], [{ ...token, gridX: 1 }, { ...token, id: 'b', gridX: 2 }]], 5).total, 5);
