# Generated by Django 6.1.1 on 2026-09-10 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        ('gravewright_maps', '0005_tile_byte_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravewright_maps.scene')),
                ('data', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('tracks', models.JSONField(default=list)),
                ('mode', models.CharField(default='sequential', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='audio/')),
                ('content_type', models.CharField(max_length=80)),
                ('duration', models.FloatField(default=0)),
                ('kind', models.CharField(default='ambience', max_length=16)),
                ('volume', models.FloatField(default=0.7)),
                ('loop', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
        ),
    ]
