# Generated by Django 6.1.1 on 2026-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fade',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='playlist',
            name='kind',
            field=models.CharField(default='playlist', max_length=12),
        ),
    ]
