# Generated by Django 6.1.1 on 2026-09-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_audio', '0002_playlist_fade_playlist_kind'),
        ('gravewright_maps', '0005_tile_byte_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_maps.assetfolder'),
        ),
    ]
