# Generated by Django 6.1.1 on 2026-09-10 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gravewright_maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneState",
            fields=[
                (
                    "scene",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="environment",
                        serialize=False,
                        to="gravewright_maps.scene",
                    ),
                ),
                ("lighting", models.JSONField(default=dict)),
                ("fog", models.JSONField(default=dict)),
                ("drawings", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="SceneObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("data", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="gravewright_maps.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(fields=["scene", "kind"], name="map_objects_kind")
                ],
            },
        ),
    ]
