# Generated by Django 6.1.1 on 2026-09-10 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        ('gravewright_maps', '0002_scenestate_sceneobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('file', models.FileField(upload_to='maps/assets/%Y/%m/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
        ),
    ]
