# Generated by Django 6.1.1 on 2026-09-10 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
        ('gravewright_maps', '0003_mapasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='mapasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_maps.assetfolder'),
        ),
    ]
