# Generated by Django 6.1.1 on 2026-09-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_maps', '0004_assetfolder_mapasset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='byte_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
