# Generated by Django 6.1.1 on 2026-09-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_audio', '0003_track_folder'),
        ('gravewright_maps', '0005_tile_byte_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='sound_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scene',
            name='soundscape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_audio.playlist'),
        ),
    ]
