# Generated by Django 6.1.1 on 2026-09-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsettings',
            name='app_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hostsettings',
            name='channels_linked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostsettings',
            name='default_locale',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='hostsettings',
            name='packages_channel',
            field=models.CharField(default='stable', max_length=10),
        ),
        migrations.AddField(
            model_name='hostsettings',
            name='privacy',
            field=models.JSONField(default=dict),
        ),
    ]
