# Generated by Django 6.1.1 on 2026-09-10 03:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gravewright_actors", "0001_initial"),
        ("gravewright_maps", "0002_scenestate_sceneobject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("linked", models.BooleanField(default=True)),
                ("snapshot", models.JSONField(default=dict)),
                ("sheet_version", models.PositiveIntegerField(default=1)),
                ("grid_x", models.FloatField(default=0)),
                ("grid_y", models.FloatField(default=0)),
                ("hidden", models.BooleanField(default=False)),
                ("locked", models.BooleanField(default=False)),
                ("rotation", models.FloatField(default=0)),
                ("elevation", models.FloatField(default=0)),
                ("disposition", models.CharField(default="neutral", max_length=10)),
                ("vision_enabled", models.BooleanField(default=True)),
                ("vision_range", models.FloatField(default=0)),
                ("conditions", models.JSONField(default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="gravewright_actors.actor",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="gravewright_maps.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
