# Generated by Django 6.1.1 on 2026-09-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_actors', '0001_initial'),
        ('gravewright_maps', '0005_tile_byte_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_maps.assetfolder'),
        ),
    ]
