# Generated by Django 6.1.1 on 2026-09-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_actors', '0001_initial'),
        ('gravewright_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyState',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravewright_campaigns.membership')),
                ('is_ready', models.BooleanField(default=False)),
                ('assets_state', models.CharField(default='unknown', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_actors.actor')),
            ],
        ),
    ]
