# Generated by Django 6.1.1 on 2026-09-10 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#c9a44c', max_length=7)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gravewright_campaigns.campaign')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_items.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=80)),
                ('system_id', models.CharField(max_length=120)),
                ('data', models.JSONField(default=dict)),
                ('permissions', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gravewright_campaigns.campaign')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravewright_items.folder')),
            ],
        ),
    ]
