# Generated by Django 6.1.1 on 2026-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
