# Generated by Django 6.1.1 on 2026-09-11 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravewright_campaigns', '0002_accesscode_max_uses_accesscode_revoked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravewright_campaigns.membership')),
                ('dismissed', models.BooleanField(default=False)),
                ('player_shown_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamerLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='campaign_valid_member_role',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('gm', 'Game master'), ('player', 'Player'), ('streamer', 'Streamer')], default='player', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['gm', 'player', 'streamer'])), name='campaign_valid_member_role'),
        ),
        migrations.AddField(
            model_name='streamerlink',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravewright_campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='streamerlink',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streamer_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
